/**
 * CHUNKED MEDIA UPLOAD ENDPOINT  (admin only)
 *
 * The browser slices the file into small pieces and posts them one at a
 * time, so a large lecture video never hits a request-size limit and never
 * times out. Ported from admin/upload_video.php.
 *
 * POST fields:
 *   upload   the chunk (multipart file field)
 *   id       16–64 char hex upload id generated by the browser
 *   index    0-based chunk number
 *   total    total number of chunks
 *   name     original file name
 *   kind     videos | pdfs | slides | resources
 *
 * Replies with JSON: {ok:true, done:false}                       (more to come)
 *                    {ok:true, done:true, file:"...", size:123}  (finished)
 *                    {ok:false, error:"..."}
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { NextResponse } from 'next/server';
import { currentUser, logActivity } from '@/lib/auth';
import { MAX_UPLOAD_SIZE } from '@/lib/config';
import { uploadUrl } from '@/lib/media';
import { humanSize } from '@/lib/text';
import { UPLOAD_PATH, ensureDir, extOf, safeFileName } from '@/lib/uploads';

export const dynamic = 'force-dynamic';

const KINDS: Record<string, string[]> = {
  videos:    ['mp4', 'webm', 'ogv', 'ogg', 'mov', 'm4v', 'mkv', 'avi'],
  pdfs:      ['pdf'],
  slides:    ['ppt', 'pptx', 'odp', 'key', 'pdf'],
  resources: ['doc', 'docx', 'odt', 'txt', 'rtf', 'pdf', 'zip', 'rar', '7z',
              'png', 'jpg', 'jpeg', 'webp', 'gif', 'xlsx', 'csv', 'mp3', 'wav', 'm4a'],
};

function reply(data: Record<string, unknown>, status = 200) {
  return NextResponse.json(data, { status, headers: { 'X-Content-Type-Options': 'nosniff' } });
}

/** A route handler has no built-in CSRF check — insist the request came from this site. */
function sameOrigin(req: Request): boolean {
  const site = req.headers.get('sec-fetch-site');
  if (site && site !== 'same-origin' && site !== 'none') return false;
  const origin = req.headers.get('origin');
  if (origin) {
    try { return new URL(origin).host === new URL(req.url).host; } catch { return false; }
  }
  return true;
}

export async function POST(req: Request) {
  /* ------------------------------ guards ------------------------------ */
  const user = await currentUser();
  if (!user || user.role !== 'admin') return reply({ ok: false, error: 'Not authorised.' }, 403);
  if (!sameOrigin(req)) return reply({ ok: false, error: 'Cross-site request refused.' }, 403);

  let fd: FormData;
  try { fd = await req.formData(); } catch { return reply({ ok: false, error: 'Chunk did not arrive.' }, 400); }

  /* ------------------------------ inputs ------------------------------ */
  const kind  = String(fd.get('kind') ?? 'videos');
  const id    = String(fd.get('id') ?? '');
  const index = parseInt(String(fd.get('index') ?? '-1'), 10);
  const total = parseInt(String(fd.get('total') ?? '0'), 10);
  const name  = String(fd.get('name') ?? '');

  if (!KINDS[kind]) return reply({ ok: false, error: 'Unknown upload type.' }, 400);
  if (!/^[a-f0-9]{16,64}$/.test(id)) return reply({ ok: false, error: 'Bad upload id.' }, 400);
  if (!(index >= 0) || total < 1 || index >= total || total > 20000) return reply({ ok: false, error: 'Bad chunk numbering.' }, 400);

  const ext = extOf(name);
  if (!KINDS[kind].includes(ext)) {
    return reply({ ok: false, error: `File type ".${ext}" is not allowed here. Allowed: ${KINDS[kind].join(', ')}` }, 415);
  }

  const chunk = fd.get('upload');
  if (!(chunk instanceof File)) return reply({ ok: false, error: 'Chunk did not arrive (missing).' }, 400);

  /* --------------------------- staging area --------------------------- */
  const tmpDir = path.join(UPLOAD_PATH, 'tmp');
  try { await ensureDir(tmpDir); } catch { return reply({ ok: false, error: 'Cannot create uploads/tmp — check folder permissions.' }, 500); }
  const part = path.join(tmpDir, id + '.part');

  /* Housekeeping: drop abandoned parts older than 24 h. */
  try {
    for (const f of await fs.readdir(tmpDir)) {
      if (!f.endsWith('.part')) continue;
      const p = path.join(tmpDir, f);
      const st = await fs.stat(p).catch(() => null);
      if (st && st.mtimeMs < Date.now() - 86400 * 1000) await fs.unlink(p).catch(() => {});
    }
  } catch { /* best effort */ }

  const exists = await fs.stat(part).then(s => s.isFile()).catch(() => false);
  if (index === 0) {
    if (exists) await fs.unlink(part).catch(() => {});      // fresh upload - start clean
  } else if (!exists) {
    return reply({ ok: false, error: 'Upload session lost. Please start the upload again.' }, 409);
  }

  /* Guard the total size while it grows. */
  const soFar = index === 0 ? 0 : (await fs.stat(part).catch(() => ({ size: 0 }))).size;
  if (soFar + chunk.size > MAX_UPLOAD_SIZE) {
    await fs.unlink(part).catch(() => {});
    return reply({ ok: false, error: `File exceeds the ${humanSize(MAX_UPLOAD_SIZE)} limit.` }, 413);
  }

  /* ------------------------- append this chunk ------------------------ */
  try {
    await fs.appendFile(part, Buffer.from(await chunk.arrayBuffer()));
  } catch {
    return reply({ ok: false, error: 'uploads/tmp is not writable.' }, 500);
  }

  /* ------------------------------ finish ------------------------------ */
  const bytes = (await fs.stat(part)).size;
  if (index < total - 1) {
    return reply({ ok: true, done: false, received: index + 1, total, bytes });
  }

  const destDir = path.join(UPLOAD_PATH, kind);
  try { await ensureDir(destDir); } catch {
    await fs.unlink(part).catch(() => {});
    return reply({ ok: false, error: `Cannot create uploads/${kind}.` }, 500);
  }

  const final = safeFileName(name, ext, kind === 'videos' ? 'video' : 'file');
  const dest = path.join(destDir, final);
  try {
    await fs.rename(part, dest);
  } catch {
    await fs.unlink(part).catch(() => {});
    return reply({ ok: false, error: 'Could not save the finished file.' }, 500);
  }

  await logActivity(user.id, 'upload', `${kind}/${final}`);
  const size = (await fs.stat(dest)).size;

  return reply({
    ok: true, done: true, file: final, path: `${kind}/${final}`,
    url: uploadUrl(`${kind}/${final}`), size, size_text: humanSize(size),
  });
}
