-- =====================================================================
--  HEALTH HOUSE — ONLINE MIDWIFERY LEARNING PORTAL
--  Database schema  |  PostgreSQL 14+
--
--  Ported from the MySQL schema of the PHP portal. Every table, column,
--  index and cascade rule is kept; only the dialect changed:
--    · AUTO_INCREMENT  -> GENERATED ALWAYS AS IDENTITY
--    · TINYINT(1)      -> BOOLEAN
--    · ENUM(...)       -> TEXT + CHECK constraint
--    · DATETIME        -> TIMESTAMPTZ
--    · ON UPDATE CURRENT_TIMESTAMP -> trigger (set_updated_at)
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 0. CLEAR ANY PREVIOUS INSTALL  (children before parents)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS quiz_attempt_answers CASCADE;
DROP TABLE IF EXISTS quiz_attempts        CASCADE;
DROP TABLE IF EXISTS quiz_options         CASCADE;
DROP TABLE IF EXISTS quiz_questions       CASCADE;
DROP TABLE IF EXISTS quizzes              CASCADE;
DROP TABLE IF EXISTS lesson_bookmarks     CASCADE;
DROP TABLE IF EXISTS lesson_progress      CASCADE;
DROP TABLE IF EXISTS lesson_subtitles     CASCADE;
DROP TABLE IF EXISTS lesson_materials     CASCADE;
DROP TABLE IF EXISTS timetable            CASCADE;
DROP TABLE IF EXISTS activity_log         CASCADE;
DROP TABLE IF EXISTS announcements        CASCADE;
DROP TABLE IF EXISTS settings             CASCADE;
DROP TABLE IF EXISTS lessons              CASCADE;
DROP TABLE IF EXISTS subjects             CASCADE;
DROP TABLE IF EXISTS users                CASCADE;
DROP TABLE IF EXISTS semesters            CASCADE;
DROP FUNCTION IF EXISTS set_updated_at();

-- "ON UPDATE CURRENT_TIMESTAMP" equivalent
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------
-- 1. SEMESTERS  (the six-semester programme)
-- ---------------------------------------------------------------------
CREATE TABLE semesters (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number      SMALLINT     NOT NULL,
  title       VARCHAR(150) NOT NULL,
  description TEXT,
  sort_order  INTEGER      NOT NULL DEFAULT 0,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_sem_number UNIQUE (number)
);

-- ---------------------------------------------------------------------
-- 2. USERS  (admins + students)
-- ---------------------------------------------------------------------
CREATE TABLE users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name     VARCHAR(120) NOT NULL,
  email         VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role          TEXT         NOT NULL DEFAULT 'student' CHECK (role IN ('admin','student')),
  student_code  VARCHAR(40),
  phone         VARCHAR(40),
  avatar        VARCHAR(255),
  semester_id   INTEGER REFERENCES semesters(id) ON DELETE SET NULL,
  status        TEXT         NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  last_login_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_users_email UNIQUE (email)
);
CREATE INDEX ix_users_role ON users(role);
CREATE INDEX ix_users_sem  ON users(semester_id);

-- ---------------------------------------------------------------------
-- 3. SUBJECTS
-- ---------------------------------------------------------------------
CREATE TABLE subjects (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id INTEGER      NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  code        VARCHAR(30),
  title       VARCHAR(180) NOT NULL,
  description TEXT,
  color       VARCHAR(20)  NOT NULL DEFAULT '#6C4CF1',
  credits     SMALLINT     NOT NULL DEFAULT 3,
  sort_order  INTEGER      NOT NULL DEFAULT 0,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_sub_sem ON subjects(semester_id);

-- ---------------------------------------------------------------------
-- 4. LESSONS  (ordered sequence inside a subject)
-- ---------------------------------------------------------------------
CREATE TABLE lessons (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id       INTEGER      NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  title            VARCHAR(200) NOT NULL,
  description      TEXT,
  content          TEXT,
  direction        TEXT         NOT NULL DEFAULT 'auto' CHECK (direction IN ('auto','ltr','rtl')),
  video_type       TEXT         NOT NULL DEFAULT 'none' CHECK (video_type IN ('none','youtube','vimeo','url','file','link')),
  video_url        VARCHAR(500),
  video_file       VARCHAR(255),
  duration_minutes INTEGER      NOT NULL DEFAULT 0,
  difficulty       TEXT         NOT NULL DEFAULT 'core' CHECK (difficulty IN ('intro','core','advanced')),
  recommended_day  INTEGER      NOT NULL DEFAULT 1,
  is_required      BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order       INTEGER      NOT NULL DEFAULT 0,
  is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_les_sub   ON lessons(subject_id);
CREATE INDEX ix_les_order ON lessons(subject_id, sort_order);

-- ---------------------------------------------------------------------
-- 5. LESSON MATERIALS  (PDF / slides / links / extra resources)
-- ---------------------------------------------------------------------
CREATE TABLE lesson_materials (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id    INTEGER      NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  type         TEXT         NOT NULL DEFAULT 'pdf' CHECK (type IN ('pdf','slides','document','link','audio','other')),
  title        VARCHAR(200) NOT NULL,
  file_path    VARCHAR(300),
  external_url VARCHAR(500),
  file_size    BIGINT       NOT NULL DEFAULT 0,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_mat_les ON lesson_materials(lesson_id);

-- ---------------------------------------------------------------------
-- 6. QUIZZES
-- ---------------------------------------------------------------------
CREATE TABLE quizzes (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id     INTEGER REFERENCES lessons(id)  ON DELETE CASCADE,
  subject_id    INTEGER REFERENCES subjects(id) ON DELETE CASCADE,
  title         VARCHAR(200) NOT NULL,
  description   TEXT,
  passing_score SMALLINT     NOT NULL DEFAULT 60,
  max_attempts  SMALLINT     NOT NULL DEFAULT 3,
  time_limit    INTEGER      NOT NULL DEFAULT 0,
  shuffle       BOOLEAN      NOT NULL DEFAULT TRUE,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_qz_les ON quizzes(lesson_id);
CREATE INDEX ix_qz_sub ON quizzes(subject_id);

-- ---------------------------------------------------------------------
-- 7. QUIZ QUESTIONS + OPTIONS
-- ---------------------------------------------------------------------
CREATE TABLE quiz_questions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id     INTEGER  NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  question    TEXT     NOT NULL,
  type        TEXT     NOT NULL DEFAULT 'single' CHECK (type IN ('single','multiple','truefalse')),
  marks       SMALLINT NOT NULL DEFAULT 1,
  explanation TEXT,
  sort_order  INTEGER  NOT NULL DEFAULT 0
);
CREATE INDEX ix_qq_quiz ON quiz_questions(quiz_id);

CREATE TABLE quiz_options (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER      NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
  option_text VARCHAR(500) NOT NULL,
  is_correct  BOOLEAN      NOT NULL DEFAULT FALSE,
  sort_order  INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX ix_qo_q ON quiz_options(question_id);

-- ---------------------------------------------------------------------
-- 8. QUIZ ATTEMPTS + ANSWERS
-- ---------------------------------------------------------------------
CREATE TABLE quiz_attempts (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id      INTEGER       NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  user_id      INTEGER       NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  score        NUMERIC(6,2)  NOT NULL DEFAULT 0,
  total_marks  NUMERIC(6,2)  NOT NULL DEFAULT 0,
  percentage   NUMERIC(5,2)  NOT NULL DEFAULT 0,
  passed       BOOLEAN       NOT NULL DEFAULT FALSE,
  started_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);
CREATE INDEX ix_qa_quiz ON quiz_attempts(quiz_id);
CREATE INDEX ix_qa_user ON quiz_attempts(user_id);

CREATE TABLE quiz_attempt_answers (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id   INTEGER NOT NULL REFERENCES quiz_attempts(id) ON DELETE CASCADE,
  question_id  INTEGER NOT NULL,
  selected_ids VARCHAR(255),
  is_correct   BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_qaa_att ON quiz_attempt_answers(attempt_id);

-- ---------------------------------------------------------------------
-- 9. LESSON PROGRESS  (the heart of the LMS)
-- ---------------------------------------------------------------------
CREATE TABLE lesson_progress (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER     NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  lesson_id     INTEGER     NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  status        TEXT        NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started','in_progress','completed')),
  video_seconds INTEGER     NOT NULL DEFAULT 0,
  started_at    TIMESTAMPTZ,
  completed_at  TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_prog UNIQUE (user_id, lesson_id)
);
CREATE INDEX ix_prog_les ON lesson_progress(lesson_id);
CREATE TRIGGER trg_prog_updated BEFORE UPDATE ON lesson_progress
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 10. TIMETABLE  (OPTIONAL guidance only - never attendance)
-- ---------------------------------------------------------------------
CREATE TABLE timetable (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id INTEGER  NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  subject_id  INTEGER  NOT NULL REFERENCES subjects(id)  ON DELETE CASCADE,
  lesson_id   INTEGER  REFERENCES lessons(id) ON DELETE SET NULL,
  day_of_week SMALLINT NOT NULL,
  start_time  TIME     NOT NULL,
  end_time    TIME     NOT NULL,
  room        VARCHAR(80),
  note        VARCHAR(255)
);
CREATE INDEX ix_tt_sem ON timetable(semester_id, day_of_week);
CREATE INDEX ix_tt_sub ON timetable(subject_id);
CREATE INDEX ix_tt_les ON timetable(lesson_id);

-- ---------------------------------------------------------------------
-- 11. ANNOUNCEMENTS / ACTIVITY LOG / SETTINGS
-- ---------------------------------------------------------------------
CREATE TABLE announcements (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  body        TEXT,
  semester_id INTEGER,
  created_by  INTEGER,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE activity_log (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER,
  action     VARCHAR(80)  NOT NULL,
  detail     VARCHAR(255),
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_log_user ON activity_log(user_id);

CREATE TABLE settings (
  skey   VARCHAR(60) PRIMARY KEY,
  svalue TEXT
);

-- ---------------------------------------------------------------------
-- 12. LESSON SUBTITLES  (WebVTT caption tracks, e.g. Pashto)
-- ---------------------------------------------------------------------
CREATE TABLE lesson_subtitles (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id  INTEGER     NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  lang       VARCHAR(10) NOT NULL DEFAULT 'ps',
  label      VARCHAR(60) NOT NULL DEFAULT 'پښتو',
  direction  TEXT        NOT NULL DEFAULT 'rtl' CHECK (direction IN ('rtl','ltr')),
  vtt        TEXT        NOT NULL,
  is_default BOOLEAN     NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_sub_lesson_lang UNIQUE (lesson_id, lang)
);
CREATE TRIGGER trg_sub_updated BEFORE UPDATE ON lesson_subtitles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- 13. SAVED LESSONS  (a student keeping a topic for later)
--     Deliberately separate from lesson_progress: saving a lesson is not
--     the same as starting it, so the two never overwrite each other.
-- ---------------------------------------------------------------------
CREATE TABLE lesson_bookmarks (
  user_id    INTEGER      NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  lesson_id  INTEGER      NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  note       VARCHAR(255),
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, lesson_id)
);
CREATE INDEX ix_bm_lesson ON lesson_bookmarks(lesson_id);

COMMIT;
